esphome:
  name: stream-server-example
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: github://oxan/esphome-stream-server

uart:
  id: uart_bus
  rx_pin: GPIO1
  tx_pin: GPIO3
  baud_rate: 115200

stream_server:
  uart_id: uart_bus
  port: 6638
